# import requests

def api_besthashtag():
    # country_codes = ['US', 'DE', 'GB', 'CA']
    # days = [7, 30, 120]

    # base_url = "https://trending-hashtags.p.rapidapi.com/api/trends/"
    # headers = {
    #     "x-rapidapi-key": "9edcbd1b9fmsha32eed8d12dc817p103628jsn9b4da960ede0",
    #     "x-rapidapi-host": "trending-hashtags.p.rapidapi.com"
    # }

    # data = []

    # for country in country_codes:
    #     for day in days:
    #         url = f"{base_url}{country}/{day}"
    #         response = requests.get(url, headers=headers)

    #         if response.status_code == 200:
    #             trends = response.json()
    #             for trend in trends:
    #                 trend_data = {
    #                     'video_views': trend.get('video_views', None),
    #                     'country_name': trend.get('country_name', None),
    #                     'industry': trend.get('industry', None),
    #                     'hashtag': trend.get('hashtag', None),
    #                     'publish_count': trend.get('publish_count', None),
    #                     'trend_type': trend.get('trend_type', None),
    #                     'is_new': trend.get('is_new', None)
    #                 }
    #                 data.append(trend_data)
    #         else:
    #             print(f"Failed to fetch data for {country} with period {day} days. Status code: {response.status_code}")

    data_df = [
        {'video_views': 106582371, 'country_name': 'United States', 'industry': None, 'hashtag': 'pinterest', 'publish_count': 21261, 'trend_type': 'flat', 'is_new': True},
        {'video_views': 322434287, 'country_name': 'United States', 'industry': 'Games', 'hashtag': 'fallout', 'publish_count': 15283, 'trend_type': 'up', 'is_new': None},
        {'video_views': 193835118, 'country_name': 'United States', 'industry': 'News & Entertainment', 'hashtag': 'sabrinacarpenter', 'publish_count': 12357, 'trend_type': 'up', 'is_new': None},
        {'video_views': 10976544, 'country_name': 'United States', 'industry': 'Sports & Outdoor', 'hashtag': 'mondaymotivation', 'publish_count': 4511, 'trend_type': 'flat', 'is_new': True},
        {'video_views': 84148154, 'country_name': 'United States', 'industry': 'News & Entertainment', 'hashtag': 'ttpd', 'publish_count': 20101, 'trend_type': 'flat', 'is_new': True},
        {'video_views': 53843081, 'country_name': 'United States', 'industry': 'Food & Beverage', 'hashtag': 'espresso', 'publish_count': 9272, 'trend_type': 'up', 'is_new': None},
        {'video_views': 26861915, 'country_name': 'United States', 'industry': 'Apparel & Accessories', 'hashtag': 'scrubs', 'publish_count': 10645, 'trend_type': 'up', 'is_new': None},
        {'video_views': 25940756, 'country_name': 'United States', 'industry': None, 'hashtag': 'surgerytiktok', 'publish_count': 9396, 'trend_type': 'up', 'is_new': None},
        {'video_views': 168852330, 'country_name': 'United States', 'industry': 'Games', 'hashtag': 'fallout4', 'publish_count': 6036, 'trend_type': 'up', 'is_new': None},
        {'video_views': 100779889, 'country_name': 'United States', 'industry': 'Games', 'hashtag': 'flightreacts', 'publish_count': 4417, 'trend_type': 'up', 'is_new': None},
        {'video_views': 18120631, 'country_name': 'United States', 'industry': 'Games', 'hashtag': 'operatingroomlife', 'publish_count': 8547, 'trend_type': 'up', 'is_new': None},
        {'video_views': 17498020, 'country_name': 'United States', 'industry': 'Games', 'hashtag': 'passingtime', 'publish_count': 8619, 'trend_type': 'up', 'is_new': None},
        {'video_views': 15134785, 'country_name': 'United States', 'industry': 'Games', 'hashtag': 'scrubtech', 'publish_count': 8592, 'trend_type': 'up', 'is_new': None},
        {'video_views': 14398894, 'country_name': 'United States', 'industry': 'Games', 'hashtag': 'offtheclock', 'publish_count': 8556, 'trend_type': 'flat', 'is_new': True},
        {'video_views': 28533059, 'country_name': 'United States', 'industry': 'Apparel & Accessories', 'hashtag': 'pinterestaesthetic', 'publish_count': 5829, 'trend_type': 'flat', 'is_new': True},
        {'video_views': 7037539, 'country_name': 'United States', 'industry': None, 'hashtag': 'happymonday', 'publish_count': 2259, 'trend_type': 'flat', 'is_new': True},
        {'video_views': 26042708, 'country_name': 'United States', 'industry': 'Apparel & Accessories', 'hashtag': 'autumn', 'publish_count': 5684, 'trend_type': 'flat', 'is_new': True},
        {'video_views': 49854227, 'country_name': 'United States', 'industry': 'Sports & Outdoor', 'hashtag': 'nbaplayoffs', 'publish_count': 9307, 'trend_type': 'flat', 'is_new': True},
        {'video_views': 15062421, 'country_name': 'United States', 'industry': None, 'hashtag': 'vibin', 'publish_count': 8105, 'trend_type': 'up', 'is_new': None},
        {'video_views': 13622688, 'country_name': 'United States', 'industry': None, 'hashtag': 'need', 'publish_count': 6808, 'trend_type': 'flat', 'is_new': True},
        {'video_views': 1686958513, 'country_name': 'United States', 'industry': 'Apparel & Accessories', 'hashtag': 'prom', 'publish_count': 102729, 'trend_type': 'up', 'is_new': None},
        {'video_views': 211166909, 'country_name': 'United States', 'industry': None, 'hashtag': 'eidmubarak', 'publish_count': 134848, 'trend_type': 'up', 'is_new': None},
        {'video_views': 204889322, 'country_name': 'United States', 'industry': None, 'hashtag': 'eid', 'publish_count': 79301, 'trend_type': 'up', 'is_new': None},
        {'video_views': 1370707954, 'country_name': 'United States', 'industry': 'News & Entertainment', 'hashtag': 'coachella', 'publish_count': 65772, 'trend_type': 'up', 'is_new': None},
        {'video_views': 488410390, 'country_name': 'United States', 'industry': 'Sports & Outdoor', 'hashtag': 'barcelona', 'publish_count': 66258, 'trend_type': 'flat', 'is_new': True},
        {'video_views': 230607079, 'country_name': 'United States', 'industry': 'Beauty & Personal Care', 'hashtag': '늙음필터', 'publish_count': 40699, 'trend_type': 'up', 'is_new': None},
        {'video_views': 644166280, 'country_name': 'United States', 'industry': None, 'hashtag': 'tiktokrizzparty', 'publish_count': 41134, 'trend_type': 'up', 'is_new': None},
        {'video_views': 643093619, 'country_name': 'United States', 'industry': 'Apparel & Accessories', 'hashtag': 'prom2024', 'publish_count': 37973, 'trend_type': 'up', 'is_new': None},
        {'video_views': 348840331, 'country_name': 'United States', 'industry': None, 'hashtag': 'thesketchreal', 'publish_count': 32815, 'trend_type': 'up', 'is_new': None},
        {'video_views': 412680053, 'country_name': 'United States', 'industry': None, 'hashtag': 'whatsupbrother', 'publish_count': 35098, 'trend_type': 'up', 'is_new': None},
        {'video_views': 220282321, 'country_name': 'United States', 'industry': None, 'hashtag': 'sketchclips', 'publish_count': 34318, 'trend_type': 'up', 'is_new': None},
        {'video_views': 134167055, 'country_name': 'United States', 'industry': None, 'hashtag': 'stevewilldoit', 'publish_count': 30516, 'trend_type': 'up', 'is_new': None},
        {'video_views': 418438703, 'country_name': 'United States', 'industry': None, 'hashtag': 'ojsimpson', 'publish_count': 20371, 'trend_type': 'up', 'is_new': None},
        {'video_views': 341956090, 'country_name': 'United States', 'industry': 'Sports & Outdoor', 'hashtag': 'ufc300', 'publish_count': 22969, 'trend_type': 'up', 'is_new': None},
        {'video_views': 17769179, 'country_name': 'United States', 'industry': 'News & Entertainment', 'hashtag': 'literie', 'publish_count': 66695, 'trend_type': 'up', 'is_new': None},
        {'video_views': 84300361, 'country_name': 'United States', 'industry': 'News & Entertainment', 'hashtag': 'marveltok', 'publish_count': 29005, 'trend_type': 'up', 'is_new': None},
        {'video_views': 131898755, 'country_name': 'United States', 'industry': None, 'hashtag': 'memory', 'publish_count': 34830, 'trend_type': 'up', 'is_new': None},
        {'video_views': 137581487, 'country_name': 'United States', 'industry': None, 'hashtag': 'trynottolaugh', 'publish_count': 24824, 'trend_type': 'up', 'is_new': None},
        {'video_views': 171112031, 'country_name': 'United States', 'industry': 'News & Entertainment', 'hashtag': 'megantheestallion', 'publish_count': 16543, 'trend_type': 'up', 'is_new': None},
        {'video_views': 104334232, 'country_name': 'United States', 'industry': 'Games', 'hashtag': 'ps2filter', 'publish_count': 31513, 'trend_type': 'up', 'is_new': None},
        {'video_views': 8510866324, 'country_name': 'United States', 'industry': None, 'hashtag': 'memecut', 'publish_count': 4622139, 'trend_type': 'flat', 'is_new': None},
        {'video_views': 2798969434, 'country_name': 'United States', 'industry': None, 'hashtag': 'สโลว์สมูท', 'publish_count': 2390108, 'trend_type': 'flat', 'is_new': None},
        {'video_views': 5209535819, 'country_name': 'United States', 'industry': None, 'hashtag': 'wlw', 'publish_count': 770505, 'trend_type': 'flat', 'is_new': None},
        {'video_views': 5131741220, 'country_name': 'United States', 'industry': 'Sports & Outdoor', 'hashtag': 'summer', 'publish_count': 2801847, 'trend_type': 'flat', 'is_new': None},
        {'video_views': 5271459563, 'country_name': 'United States', 'industry': None, 'hashtag': 'work', 'publish_count': 572533, 'trend_type': 'up', 'is_new': None},
        {'video_views': 3490188560, 'country_name': 'United States', 'industry': 'News & Entertainment', 'hashtag': 'newmusic', 'publish_count': 608871, 'trend_type': 'up', 'is_new': None},
        {'video_views': 5539088503, 'country_name': 'United States', 'industry': 'Sports & Outdoor', 'hashtag': 'baseball', 'publish_count': 435204, 'trend_type': 'up', 'is_new': None},
        {'video_views': 2952205178, 'country_name': 'United States', 'industry': 'Baby, Kids & Maternity', 'hashtag': 'boymom', 'publish_count': 565721, 'trend_type': 'up', 'is_new': None},
        {'video_views': 3468138314, 'country_name': 'United States', 'industry': 'Games', 'hashtag': 'warzone', 'publish_count': 524260, 'trend_type': 'up', 'is_new': None},
        {'video_views': 3949411239, 'country_name': 'United States', 'industry': None, 'hashtag': 'losangeles', 'publish_count': 512301, 'trend_type': 'up', 'is_new': None},
        {'video_views': 3529575011, 'country_name': 'United States', 'industry': None, 'hashtag': 'r6', 'publish_count': 450631, 'trend_type': 'up', 'is_new': None},
        {'video_views': 3815643085, 'country_name': 'United States', 'industry': None, 'hashtag': 'country', 'publish_count': 421418, 'trend_type': 'up', 'is_new': None},
        {'video_views': 3068269871, 'country_name': 'United States', 'industry': 'Baby, Kids & Maternity', 'hashtag': 'sahm', 'publish_count': 620248, 'trend_type': 'up', 'is_new': None},
        {'video_views': 1441320324, 'country_name': 'United States', 'industry': None, 'hashtag': 'inverted', 'publish_count': 215517, 'trend_type': 'up', 'is_new': None},
        {'video_views': 3704210514, 'country_name': 'United States', 'industry': 'Games', 'hashtag': 'rainbowsixsiege', 'publish_count': 403087, 'trend_type': 'up', 'is_new': None},
        {'video_views': 3071551882, 'country_name': 'United States', 'industry': None, 'hashtag': 'contenido', 'publish_count': 445156, 'trend_type': 'up', 'is_new': None},
        {'video_views': 1834261605, 'country_name': 'United States', 'industry': 'Apparel & Accessories', 'hashtag': 'spring', 'publish_count': 545651, 'trend_type': 'up', 'is_new': None},
        {'video_views': 2446163977, 'country_name': 'United States', 'industry': None, 'hashtag': 'easter', 'publish_count': 450818, 'trend_type': 'up', 'is_new': None},
        {'video_views': 2186997065, 'country_name': 'United States', 'industry': 'Travel', 'hashtag': 'beach', 'publish_count': 410303, 'trend_type': 'up', 'is_new': None},
        {'video_views': 1049166517, 'country_name': 'United States', 'industry': None, 'hashtag': 'unfrezzmyaccount', 'publish_count': 748836, 'trend_type': 'up', 'is_new': None},
        {'video_views': 8938616, 'country_name': 'Germany', 'industry': 'Games', 'hashtag': 'montag', 'publish_count': 1394, 'trend_type': 'flat', 'is_new': True},
        {'video_views': 20762135, 'country_name': 'Germany', 'industry': 'Sports & Outdoor', 'hashtag': 'pedro', 'publish_count': 2909, 'trend_type': 'up', 'is_new': None},
        {'video_views': 7906516, 'country_name': 'Germany', 'industry': None, 'hashtag': 'marmariemmanuel', 'publish_count': 573, 'trend_type': 'flat', 'is_new': True},
        {'video_views': 9796359, 'country_name': 'Germany', 'industry': 'News & Entertainment', 'hashtag': 'bushido', 'publish_count': 1152, 'trend_type': 'flat', 'is_new': True},
        {'video_views': 19000043, 'country_name': 'Germany', 'industry': None, 'hashtag': 'abitur2024', 'publish_count': 1070, 'trend_type': 'flat', 'is_new': True},
        {'video_views': 1921725, 'country_name': 'Germany', 'industry': None, 'hashtag': 'videoaleatorio', 'publish_count': 651, 'trend_type': 'flat', 'is_new': True},
        {'video_views': 984598, 'country_name': 'Germany', 'industry': None, 'hashtag': 'howpinterestseesme', 'publish_count': 863, 'trend_type': 'up', 'is_new': None},
        {'video_views': 3096155, 'country_name': 'Germany', 'industry': None, 'hashtag': 'bishop', 'publish_count': 204, 'trend_type': 'flat', 'is_new': True},
        {'video_views': 1662669, 'country_name': 'Germany', 'industry': None, 'hashtag': 'mira', 'publish_count': 515, 'trend_type': 'up', 'is_new': None},
        {'video_views': 10642796, 'country_name': 'Germany', 'industry': None, 'hashtag': 'sydney', 'publish_count': 503, 'trend_type': 'flat', 'is_new': True},
        {'video_views': 976917, 'country_name': 'Germany', 'industry': 'Sports & Outdoor', 'hashtag': 'mondaymotivation', 'publish_count': 269, 'trend_type': 'flat', 'is_new': True},
        {'video_views': 12376718, 'country_name': 'Germany', 'industry': 'Sports & Outdoor', 'hashtag': 'leonmachere', 'publish_count': 340, 'trend_type': 'flat', 'is_new': True},
        {'video_views': 18787709, 'country_name': 'Germany', 'industry': 'Games', 'hashtag': 'fallout', 'publish_count': 624, 'trend_type': 'up', 'is_new': None},
        {'video_views': 5099686, 'country_name': 'Germany', 'industry': 'News & Entertainment', 'hashtag': 'ttpd', 'publish_count': 1309, 'trend_type': 'flat', 'is_new': True},
        {'video_views': 278844, 'country_name': 'Germany', 'industry': None, 'hashtag': 'wochenstart', 'publish_count': 255, 'trend_type': 'flat', 'is_new': True},
        {'video_views': 5276734, 'country_name': 'Germany', 'industry': 'Games', 'hashtag': 'attack', 'publish_count': 253, 'trend_type': 'up', 'is_new': None},
        {'video_views': 3235161, 'country_name': 'Germany', 'industry': None, 'hashtag': 'bishopmarmariemmanuel', 'publish_count': 145, 'trend_type': 'flat', 'is_new': True},
        {'video_views': 7624862, 'country_name': 'Germany', 'industry': 'Vehicle & Transportation', 'hashtag': 'blitzer', 'publish_count': 289, 'trend_type': 'flat', 'is_new': True},
        {'video_views': 771742, 'country_name': 'Germany', 'industry': None, 'hashtag': 'petite', 'publish_count': 1389, 'trend_type': 'flat', 'is_new': True},
        {'video_views': 512526, 'country_name': 'Germany', 'industry': None, 'hashtag': 'toietmoi', 'publish_count': 206, 'trend_type': 'flat', 'is_new': True},
        {'video_views': 145945931, 'country_name': 'Germany', 'industry': None, 'hashtag': 'eidmubarak', 'publish_count': 22348, 'trend_type': 'flat', 'is_new': None},
        {'video_views': 105506236, 'country_name': 'Germany', 'industry': None, 'hashtag': 'eid', 'publish_count': 13153, 'trend_type': 'flat', 'is_new': None},
        {'video_views': 57242777, 'country_name': 'Germany', 'industry': None, 'hashtag': 'bayram', 'publish_count': 6329, 'trend_type': 'flat', 'is_new': None},
        {'video_views': 92931178, 'country_name': 'Germany', 'industry': 'Sports & Outdoor', 'hashtag': 'leverkusen', 'publish_count': 7805, 'trend_type': 'flat', 'is_new': True},
        {'video_views': 44647130, 'country_name': 'Germany', 'industry': None, 'hashtag': 'عيد_سعيد', 'publish_count': 6384, 'trend_type': 'flat', 'is_new': None},
        {'video_views': 39116193, 'country_name': 'Germany', 'industry': None, 'hashtag': 'عيد_الفطر_المبارك', 'publish_count': 6209, 'trend_type': 'flat', 'is_new': None},
        {'video_views': 32456460, 'country_name': 'Germany', 'industry': None, 'hashtag': 'كل_عام_وانتم_بخير', 'publish_count': 5618, 'trend_type': 'flat', 'is_new': None},
        {'video_views': 27652946, 'country_name': 'Germany', 'industry': None, 'hashtag': 'عيد_مبارك', 'publish_count': 5355, 'trend_type': 'flat', 'is_new': None},
        {'video_views': 39273565, 'country_name': 'Germany', 'industry': 'Pets', 'hashtag': 'waschbär', 'publish_count': 3726, 'trend_type': 'up', 'is_new': None},
        {'video_views': 27793642, 'country_name': 'Germany', 'industry': None, 'hashtag': 'عيد', 'publish_count': 4050, 'trend_type': 'flat', 'is_new': None},
        {'video_views': 26172090, 'country_name': 'Germany', 'industry': None, 'hashtag': 'dardan', 'publish_count': 2439, 'trend_type': 'flat', 'is_new': None},
        {'video_views': 6244992, 'country_name': 'Germany', 'industry': None, 'hashtag': 'foryoufest', 'publish_count': 5614, 'trend_type': 'flat', 'is_new': None},
        {'video_views': 85446365, 'country_name': 'Germany', 'industry': 'Sports & Outdoor', 'hashtag': 'ucl', 'publish_count': 4513, 'trend_type': 'flat', 'is_new': True},
        {'video_views': 35121723, 'country_name': 'Germany', 'industry': None, 'hashtag': 'mero', 'publish_count': 2171, 'trend_type': 'flat', 'is_new': None},
        {'video_views': 100796295, 'country_name': 'Germany', 'industry': None, 'hashtag': 'inverted', 'publish_count': 2335, 'trend_type': 'flat', 'is_new': None},
        {'video_views': 42142630, 'country_name': 'Germany', 'industry': None, 'hashtag': 'eclipse', 'publish_count': 1881, 'trend_type': 'flat', 'is_new': None},
        {'video_views': 33977649, 'country_name': 'Germany', 'industry': 'Games', 'hashtag': 'väter', 'publish_count': 8609, 'trend_type': 'flat', 'is_new': None},
        {'video_views': 29300328, 'country_name': 'Germany', 'industry': None, 'hashtag': 'yourfavorite', 'publish_count': 9009, 'trend_type': 'flat', 'is_new': None},
        {'video_views': 29835961, 'country_name': 'Germany', 'industry': None, 'hashtag': 'wortwitze', 'publish_count': 9067, 'trend_type': 'flat', 'is_new': None},
        {'video_views': 52003059, 'country_name': 'Germany', 'industry': 'Sports & Outdoor', 'hashtag': 'bayerleverkusen', 'publish_count': 2716, 'trend_type': 'up', 'is_new': None},
        {'video_views': 873258121, 'country_name': 'Germany', 'industry': None, 'hashtag': 'สโลว์สมูท', 'publish_count': 358845, 'trend_type': 'flat', 'is_new': True},
        {'video_views': 2053049563, 'country_name': 'Germany', 'industry': 'Games', 'hashtag': 'brawlstars', 'publish_count': 196559, 'trend_type': 'flat', 'is_new': None},
        {'video_views': 983509722, 'country_name': 'Germany', 'industry': 'Sports & Outdoor', 'hashtag': 'summer', 'publish_count': 1457281, 'trend_type': 'flat', 'is_new': None},
        {'video_views': 1081580344, 'country_name': 'Germany', 'industry': None, 'hashtag': 'frankfurt', 'publish_count': 148587, 'trend_type': 'flat', 'is_new': None},
        {'video_views': 2081838710, 'country_name': 'Germany', 'industry': None, 'hashtag': 'schule', 'publish_count': 89108, 'trend_type': 'flat', 'is_new': None},
        {'video_views': 631987095, 'country_name': 'Germany', 'industry': None, 'hashtag': 'sommer', 'publish_count': 95778, 'trend_type': 'flat', 'is_new': None},
        {'video_views': 1573488320, 'country_name': 'Germany', 'industry': 'Sports & Outdoor', 'hashtag': 'fussball', 'publish_count': 89387, 'trend_type': 'flat', 'is_new': None},
        {'video_views': 692180615, 'country_name': 'Germany', 'industry': None, 'hashtag': 'valentinesday', 'publish_count': 66692, 'trend_type': 'flat', 'is_new': None},
        {'video_views': 1028880176, 'country_name': 'Germany', 'industry': 'Apparel & Accessories', 'hashtag': 'ootd', 'publish_count': 100252, 'trend_type': 'flat', 'is_new': None},
        {'video_views': 961817268, 'country_name': 'Germany', 'industry': 'Sports & Outdoor', 'hashtag': 'fußball', 'publish_count': 74535, 'trend_type': 'flat', 'is_new': None},
        {'video_views': 888739865, 'country_name': 'Germany', 'industry': 'Apparel & Accessories', 'hashtag': 'outfit', 'publish_count': 76589, 'trend_type': 'flat', 'is_new': None},
        {'video_views': 676285998, 'country_name': 'Germany', 'industry': 'Sports & Outdoor', 'hashtag': 'bayern', 'publish_count': 84954, 'trend_type': 'up', 'is_new': None},
        {'video_views': 586687277, 'country_name': 'Germany', 'industry': 'Sports & Outdoor', 'hashtag': 'abnehmen', 'publish_count': 113030, 'trend_type': 'up', 'is_new': None},
        {'video_views': 671826957, 'country_name': 'Germany', 'industry': 'Games', 'hashtag': 'brawlstarstiktok', 'publish_count': 73705, 'trend_type': 'up', 'is_new': None},
        {'video_views': 587109946, 'country_name': 'Germany', 'industry': 'Sports & Outdoor', 'hashtag': 'realmadrid', 'publish_count': 56822, 'trend_type': 'up', 'is_new': None},
        {'video_views': 813414514, 'country_name': 'Germany', 'industry': 'Sports & Outdoor', 'hashtag': 'bundesliga', 'publish_count': 50465, 'trend_type': 'up', 'is_new': None},
        {'video_views': 454014367, 'country_name': 'Germany', 'industry': None, 'hashtag': 'nürnberg', 'publish_count': 44928, 'trend_type': 'up', 'is_new': None},
        {'video_views': 463747705, 'country_name': 'Germany', 'industry': 'Vehicle & Transportation', 'hashtag': 'motorcycle', 'publish_count': 54423, 'trend_type': 'up', 'is_new': None},
        {'video_views': 333759540, 'country_name': 'Germany', 'industry': None, 'hashtag': 'mylove', 'publish_count': 48913, 'trend_type': 'up', 'is_new': None},
        {'video_views': 392597112, 'country_name': 'Germany', 'industry': None, 'hashtag': 'bs', 'publish_count': 57776, 'trend_type': 'up', 'is_new': None},
        {'video_views': 23912551, 'country_name': 'United Kingdom', 'industry': 'News & Entertainment', 'hashtag': 'lexi', 'publish_count': 6039, 'trend_type': 'up', 'is_new': None},
        {'video_views': 17106066, 'country_name': 'United Kingdom', 'industry': None, 'hashtag': 'vile', 'publish_count': 3611, 'trend_type': 'up', 'is_new': None},
        {'video_views': 54266735, 'country_name': 'United Kingdom', 'industry': 'News & Entertainment', 'hashtag': 'sabrinacarpenter', 'publish_count': 4482, 'trend_type': 'up', 'is_new': None},
        {'video_views': 65944428, 'country_name': 'United Kingdom', 'industry': 'Games', 'hashtag': 'fallout', 'publish_count': 3527, 'trend_type': 'up', 'is_new': None},
        {'video_views': 2398885, 'country_name': 'United Kingdom', 'industry': None, 'hashtag': 'howpinterestseesme', 'publish_count': 3078, 'trend_type': 'up', 'is_new': None},
        {'video_views': 3959958, 'country_name': 'United Kingdom', 'industry': 'News & Entertainment', 'hashtag': 'hazey', 'publish_count': 2529, 'trend_type': 'flat', 'is_new': True},
        {'video_views': 2043793, 'country_name': 'United Kingdom', 'industry': 'Sports & Outdoor', 'hashtag': 'mondaymotivation', 'publish_count': 1163, 'trend_type': 'flat', 'is_new': True},
        {'video_views': 11278144, 'country_name': 'United Kingdom', 'industry': None, 'hashtag': 'justice', 'publish_count': 1925, 'trend_type': 'flat', 'is_new': True},
        {'video_views': 9533424, 'country_name': 'United Kingdom', 'industry': 'Apparel & Accessories', 'hashtag': 'pinterestaesthetic', 'publish_count': 2776, 'trend_type': 'flat', 'is_new': True},
        {'video_views': 3717885, 'country_name': 'United Kingdom', 'industry': None, 'hashtag': 'poorboy', 'publish_count': 800, 'trend_type': 'up', 'is_new': None},
        {'video_views': 3344493, 'country_name': 'United Kingdom', 'industry': None, 'hashtag': 'disgusting', 'publish_count': 1148, 'trend_type': 'up', 'is_new': None},
        {'video_views': 14917550, 'country_name': 'United Kingdom', 'industry': 'Food & Beverage', 'hashtag': 'espresso', 'publish_count': 3171, 'trend_type': 'up', 'is_new': None},
        {'video_views': 6458332, 'country_name': 'United Kingdom', 'industry': 'Games', 'hashtag': 'jumped', 'publish_count': 589, 'trend_type': 'flat', 'is_new': True},
        {'video_views': 1305089, 'country_name': 'United Kingdom', 'industry': None, 'hashtag': '97', 'publish_count': 691, 'trend_type': 'flat', 'is_new': True},
        {'video_views': 8753472, 'country_name': 'United Kingdom', 'industry': None, 'hashtag': 'ukweather', 'publish_count': 1313, 'trend_type': 'flat', 'is_new': True},
        {'video_views': 5037597, 'country_name': 'United Kingdom', 'industry': None, 'hashtag': 'horrible', 'publish_count': 801, 'trend_type': 'up', 'is_new': None},
        {'video_views': 4296825, 'country_name': 'United Kingdom', 'industry': 'Games', 'hashtag': 'bitethecurb', 'publish_count': 713, 'trend_type': 'flat', 'is_new': True},
        {'video_views': 3623669, 'country_name': 'United Kingdom', 'industry': None, 'hashtag': '8', 'publish_count': 983, 'trend_type': 'flat', 'is_new': True},
        {'video_views': 5822344, 'country_name': 'United Kingdom', 'industry': None, 'hashtag': 'alex', 'publish_count': 1625, 'trend_type': 'flat', 'is_new': True},
        {'video_views': 43700450, 'country_name': 'United Kingdom', 'industry': None, 'hashtag': 'sydney', 'publish_count': 981, 'trend_type': 'flat', 'is_new': True},
        {'video_views': 326216554, 'country_name': 'United Kingdom', 'industry': None, 'hashtag': 'eid', 'publish_count': 74615, 'trend_type': 'flat', 'is_new': None},
        {'video_views': 246616932, 'country_name': 'United Kingdom', 'industry': None, 'hashtag': 'eidmubarak', 'publish_count': 84467, 'trend_type': 'flat', 'is_new': None},
        {'video_views': 122213912, 'country_name': 'United Kingdom', 'industry': None, 'hashtag': 'bengali', 'publish_count': 10589, 'trend_type': 'flat', 'is_new': None},
        {'video_views': 60545377, 'country_name': 'United Kingdom', 'industry': None, 'hashtag': 'eid2024', 'publish_count': 14865, 'trend_type': 'flat', 'is_new': None},
        {'video_views': 100773994, 'country_name': 'United Kingdom', 'industry': None, 'hashtag': 'eclipse', 'publish_count': 8394, 'trend_type': 'flat', 'is_new': None},
        {'video_views': 65539513, 'country_name': 'United Kingdom', 'industry': 'Apparel & Accessories', 'hashtag': 'eidoutfit', 'publish_count': 11661, 'trend_type': 'flat', 'is_new': None},
        {'video_views': 65377886, 'country_name': 'United Kingdom', 'industry': 'Apparel & Accessories', 'hashtag': 'henna', 'publish_count': 10725, 'trend_type': 'flat', 'is_new': None},
        {'video_views': 48156504, 'country_name': 'United Kingdom', 'industry': 'Apparel & Accessories', 'hashtag': 'mehndi', 'publish_count': 8385, 'trend_type': 'flat', 'is_new': None},
        {'video_views': 199334605, 'country_name': 'United Kingdom', 'industry': 'News & Entertainment', 'hashtag': 'coachella', 'publish_count': 7669, 'trend_type': 'up', 'is_new': None},
        {'video_views': 46127072, 'country_name': 'United Kingdom', 'industry': 'News & Entertainment', 'hashtag': 'mazerunner', 'publish_count': 7936, 'trend_type': 'up', 'is_new': None},
        {'video_views': 70934264, 'country_name': 'United Kingdom', 'industry': 'Sports & Outdoor', 'hashtag': 'ufc300', 'publish_count': 7820, 'trend_type': 'up', 'is_new': None},
        {'video_views': 77395470, 'country_name': 'United Kingdom', 'industry': 'News & Entertainment', 'hashtag': 'sabrinacarpenter', 'publish_count': 6549, 'trend_type': 'up', 'is_new': None},
        {'video_views': 75122553, 'country_name': 'United Kingdom', 'industry': 'Games', 'hashtag': 'rapunzel', 'publish_count': 4008, 'trend_type': 'up', 'is_new': None},
        {'video_views': 69328194, 'country_name': 'United Kingdom', 'industry': None, 'hashtag': 'leahhalton', 'publish_count': 4157, 'trend_type': 'up', 'is_new': None},
        {'video_views': 27922724, 'country_name': 'United Kingdom', 'industry': 'Apparel & Accessories', 'hashtag': 'hennaartist', 'publish_count': 5183, 'trend_type': 'up', 'is_new': None},
        {'video_views': 47256335, 'country_name': 'United Kingdom', 'industry': None, 'hashtag': 'thenurserynurse', 'publish_count': 5504, 'trend_type': 'up', 'is_new': None},
        {'video_views': 145397338, 'country_name': 'United Kingdom', 'industry': None, 'hashtag': 'inverted', 'publish_count': 2652, 'trend_type': 'up', 'is_new': None},
        {'video_views': 29251903, 'country_name': 'United Kingdom', 'industry': 'News & Entertainment', 'hashtag': 'ttpd', 'publish_count': 8349, 'trend_type': 'up', 'is_new': None},
        {'video_views': 31343037, 'country_name': 'United Kingdom', 'industry': 'News & Entertainment', 'hashtag': 'bobmarley', 'publish_count': 3500, 'trend_type': 'up', 'is_new': None},
        {'video_views': 39376897, 'country_name': 'United Kingdom', 'industry': 'News & Entertainment', 'hashtag': 'themazerunner', 'publish_count': 4944, 'trend_type': 'up', 'is_new': None},
        {'video_views': 2640008036, 'country_name': 'United Kingdom', 'industry': None, 'hashtag': 'memecut', 'publish_count': 1109969, 'trend_type': 'flat', 'is_new': None},
        {'video_views': 4629732638, 'country_name': 'United Kingdom', 'industry': 'Apparel & Accessories', 'hashtag': 'tiktokmademebuyit', 'publish_count': 641227, 'trend_type': 'up', 'is_new': None},
        {'video_views': 511807494, 'country_name': 'United Kingdom', 'industry': None, 'hashtag': 'สโลว์สมูท', 'publish_count': 319420, 'trend_type': 'up', 'is_new': None},
        {'video_views': 1761977096, 'country_name': 'United Kingdom', 'industry': 'Sports & Outdoor', 'hashtag': 'summer', 'publish_count': 1027441, 'trend_type': 'up', 'is_new': None},
        {'video_views': 1928499375, 'country_name': 'United Kingdom', 'industry': 'Sports & Outdoor', 'hashtag': 'liverpool', 'publish_count': 249907, 'trend_type': 'up', 'is_new': None},
        {'video_views': 2397047344, 'country_name': 'United Kingdom', 'industry': 'Apparel & Accessories', 'hashtag': 'tiktokshop', 'publish_count': 540963, 'trend_type': 'up', 'is_new': None},
        {'video_views': 1883333713, 'country_name': 'United Kingdom', 'industry': 'Apparel & Accessories', 'hashtag': 'ootd', 'publish_count': 424389, 'trend_type': 'up', 'is_new': None},
        {'video_views': 1902709506, 'country_name': 'United Kingdom', 'industry': 'Baby, Kids & Maternity', 'hashtag': 'mumsoftiktok', 'publish_count': 273680, 'trend_type': 'up', 'is_new': None},
        {'video_views': 1301986122, 'country_name': 'United Kingdom', 'industry': 'Travel', 'hashtag': 'holiday', 'publish_count': 200685, 'trend_type': 'up', 'is_new': None},
        {'video_views': 855007072, 'country_name': 'United Kingdom', 'industry': 'Apparel & Accessories', 'hashtag': 'smallbusiness', 'publish_count': 306797, 'trend_type': 'up', 'is_new': None},
        {'video_views': 1376737918, 'country_name': 'United Kingdom', 'industry': None, 'hashtag': 'valentinesday', 'publish_count': 200761, 'trend_type': 'up', 'is_new': None},
        {'video_views': 1050824486, 'country_name': 'United Kingdom', 'industry': 'News & Entertainment', 'hashtag': 'newmusic', 'publish_count': 175229, 'trend_type': 'up', 'is_new': None},
        {'video_views': 836961737, 'country_name': 'United Kingdom', 'industry': None, 'hashtag': 'unitedkingdom', 'publish_count': 218089, 'trend_type': 'up', 'is_new': None},
        {'video_views': 879886057, 'country_name': 'United Kingdom', 'industry': None, 'hashtag': 'r6', 'publish_count': 146639, 'trend_type': 'up', 'is_new': None},
        {'video_views': 1109718128, 'country_name': 'United Kingdom', 'industry': 'Travel', 'hashtag': 'traveltiktok', 'publish_count': 149202, 'trend_type': 'up', 'is_new': None},
        {'video_views': 879268090, 'country_name': 'United Kingdom', 'industry': 'Games', 'hashtag': 'hazbinhotel', 'publish_count': 147801, 'trend_type': 'up', 'is_new': None},
        {'video_views': 666749080, 'country_name': 'United Kingdom', 'industry': None, 'hashtag': 'pretty', 'publish_count': 92522, 'trend_type': 'up', 'is_new': None},
        {'video_views': 630176085, 'country_name': 'United Kingdom', 'industry': 'Sports & Outdoor', 'hashtag': 'horse', 'publish_count': 125816, 'trend_type': 'up', 'is_new': None},
        {'video_views': 901709755, 'country_name': 'United Kingdom', 'industry': 'Games', 'hashtag': 'rainbowsixsiege', 'publish_count': 115523, 'trend_type': 'up', 'is_new': None},
        {'video_views': 892545997, 'country_name': 'United Kingdom', 'industry': 'Baby, Kids & Maternity', 'hashtag': 'mumlife', 'publish_count': 131164, 'trend_type': 'up', 'is_new': None},
        {'video_views': 12230840, 'country_name': 'Canada', 'industry': None, 'hashtag': 'pinterest', 'publish_count': 3967, 'trend_type': 'flat', 'is_new': True},
        {'video_views': 5892278, 'country_name': 'Canada', 'industry': 'Food & Beverage', 'hashtag': 'maplesyrup', 'publish_count': 18520, 'trend_type': 'up', 'is_new': None},
        {'video_views': 2696758, 'country_name': 'Canada', 'industry': 'Sports & Outdoor', 'hashtag': 'drakediss', 'publish_count': 2065, 'trend_type': 'up', 'is_new': None},
        {'video_views': 8223284, 'country_name': 'Canada', 'industry': 'Beauty & Personal Care', 'hashtag': '늙음필터', 'publish_count': 1027, 'trend_type': 'flat', 'is_new': True},
        {'video_views': 806569, 'country_name': 'Canada', 'industry': None, 'hashtag': 'howpinterestseesme', 'publish_count': 1123, 'trend_type': 'up', 'is_new': None},
        {'video_views': 20744771, 'country_name': 'Canada', 'industry': 'News & Entertainment', 'hashtag': 'sabrinacarpenter', 'publish_count': 1051, 'trend_type': 'up', 'is_new': None},
        {'video_views': 4173531, 'country_name': 'Canada', 'industry': 'Apparel & Accessories', 'hashtag': 'pinterestaesthetic', 'publish_count': 947, 'trend_type': 'flat', 'is_new': True},
        {'video_views': 22469283, 'country_name': 'Canada', 'industry': 'Games', 'hashtag': 'fallout', 'publish_count': 1011, 'trend_type': 'up', 'is_new': None},
        {'video_views': 11457332, 'country_name': 'Canada', 'industry': None, 'hashtag': 'chamkila', 'publish_count': 801, 'trend_type': 'up', 'is_new': None},
        {'video_views': 7703708, 'country_name': 'Canada', 'industry': 'News & Entertainment', 'hashtag': 'ttpd', 'publish_count': 1595, 'trend_type': 'flat', 'is_new': True},
        {'video_views': 6446148, 'country_name': 'Canada', 'industry': 'Food & Beverage', 'hashtag': 'espresso', 'publish_count': 927, 'trend_type': 'up', 'is_new': None},
        {'video_views': 562530, 'country_name': 'Canada', 'industry': 'Sports & Outdoor', 'hashtag': 'mondaymotivation', 'publish_count': 357, 'trend_type': 'flat', 'is_new': True},
        {'video_views': 14261419, 'country_name': 'Canada', 'industry': None, 'hashtag': 'whatsupbrother', 'publish_count': 955, 'trend_type': 'up', 'is_new': None},
        {'video_views': 873233, 'country_name': 'Canada', 'industry': None, 'hashtag': 'pintrest', 'publish_count': 415, 'trend_type': 'up', 'is_new': None},
        {'video_views': 3500001, 'country_name': 'Canada', 'industry': None, 'hashtag': 'marmariemmanuel', 'publish_count': 170, 'trend_type': 'flat', 'is_new': True},
        {'video_views': 2525286, 'country_name': 'Canada', 'industry': 'News & Entertainment', 'hashtag': 'disstrack', 'publish_count': 696, 'trend_type': 'up', 'is_new': None},
        {'video_views': 348150, 'country_name': 'Canada', 'industry': None, 'hashtag': 'motivationmonday', 'publish_count': 317, 'trend_type': 'flat', 'is_new': True},
        {'video_views': 3907238, 'country_name': 'Canada', 'industry': None, 'hashtag': 'exams', 'publish_count': 447, 'trend_type': 'flat', 'is_new': True},
        {'video_views': 303493, 'country_name': 'Canada', 'industry': None, 'hashtag': 'pinteresttrend', 'publish_count': 278, 'trend_type': 'flat', 'is_new': True},
        {'video_views': 11524181, 'country_name': 'Canada', 'industry': 'Games', 'hashtag': 'fallout4', 'publish_count': 366, 'trend_type': 'up', 'is_new': None},
        {'video_views': 55734651, 'country_name': 'Canada', 'industry': None, 'hashtag': 'eid', 'publish_count': 13943, 'trend_type': 'up', 'is_new': None},
        {'video_views': 46416227, 'country_name': 'Canada', 'industry': None, 'hashtag': 'eidmubarak', 'publish_count': 11485, 'trend_type': 'up', 'is_new': None},
        {'video_views': 46914611, 'country_name': 'Canada', 'industry': None, 'hashtag': 'pinterest', 'publish_count': 7329, 'trend_type': 'flat', 'is_new': True},
        {'video_views': 18834358, 'country_name': 'Canada', 'industry': 'Pets', 'hashtag': 'dogsofttiktok', 'publish_count': 4037, 'trend_type': 'flat', 'is_new': True},
        {'video_views': 119535133, 'country_name': 'Canada', 'industry': 'News & Entertainment', 'hashtag': 'coachella', 'publish_count': 3039, 'trend_type': 'up', 'is_new': None},
        {'video_views': 10649879, 'country_name': 'Canada', 'industry': 'Beauty & Personal Care', 'hashtag': '늙음필터', 'publish_count': 1531, 'trend_type': 'up', 'is_new': None},
        {'video_views': 21256832, 'country_name': 'Canada', 'industry': 'Beauty & Personal Care', 'hashtag': 'sephorahaul', 'publish_count': 2452, 'trend_type': 'up', 'is_new': None},
        {'video_views': 13142059, 'country_name': 'Canada', 'industry': 'Vehicle & Transportation', 'hashtag': 'tiger', 'publish_count': 10069, 'trend_type': 'up', 'is_new': None},
        {'video_views': 9083021, 'country_name': 'Canada', 'industry': None, 'hashtag': 'eid2024', 'publish_count': 2845, 'trend_type': 'up', 'is_new': None},
        {'video_views': 15334715, 'country_name': 'Canada', 'industry': 'Apparel & Accessories', 'hashtag': 'henna', 'publish_count': 1959, 'trend_type': 'up', 'is_new': None},
        {'video_views': 10255698, 'country_name': 'Canada', 'industry': 'Apparel & Accessories', 'hashtag': 'eidoutfit', 'publish_count': 2148, 'trend_type': 'up', 'is_new': None},
        {'video_views': 30551095, 'country_name': 'Canada', 'industry': 'Sports & Outdoor', 'hashtag': 'ufc300', 'publish_count': 1746, 'trend_type': 'up', 'is_new': None},
        {'video_views': 15848585, 'country_name': 'Canada', 'industry': 'Apparel & Accessories', 'hashtag': 'pinterestaesthetic', 'publish_count': 1941, 'trend_type': 'flat', 'is_new': True},
        {'video_views': 32878975, 'country_name': 'Canada', 'industry': 'News & Entertainment', 'hashtag': 'sabrinacarpenter', 'publish_count': 1523, 'trend_type': 'up', 'is_new': None},
        {'video_views': 8467485, 'country_name': 'Canada', 'industry': 'Food & Beverage', 'hashtag': 'maplesyrup', 'publish_count': 19042, 'trend_type': 'up', 'is_new': None},
        {'video_views': 1813321, 'country_name': 'Canada', 'industry': None, 'hashtag': 'timewarpscan', 'publish_count': 2020, 'trend_type': 'up', 'is_new': None},
        {'video_views': 27002397, 'country_name': 'Canada', 'industry': None, 'hashtag': 'leahhalton', 'publish_count': 1081, 'trend_type': 'up', 'is_new': None},
        {'video_views': 3482776, 'country_name': 'Canada', 'industry': None, 'hashtag': '410', 'publish_count': 2122, 'trend_type': 'up', 'is_new': None},
        {'video_views': 7080817, 'country_name': 'Canada', 'industry': None, 'hashtag': 'عيد_سعيد', 'publish_count': 1762, 'trend_type': 'up', 'is_new': None},
        {'video_views': 17840009, 'country_name': 'Canada', 'industry': 'Sports & Outdoor', 'hashtag': 'ucl', 'publish_count': 1582, 'trend_type': 'flat', 'is_new': True},
        {'video_views': 734087956, 'country_name': 'Canada', 'industry': None, 'hashtag': 'memecut', 'publish_count': 248202, 'trend_type': 'flat', 'is_new': None},
        {'video_views': 525454319, 'country_name': 'Canada', 'industry': 'Sports & Outdoor', 'hashtag': 'summer', 'publish_count': 941584, 'trend_type': 'up', 'is_new': None},
        {'video_views': 696947559, 'country_name': 'Canada', 'industry': 'Apparel & Accessories', 'hashtag': 'ootd', 'publish_count': 83486, 'trend_type': 'flat', 'is_new': True},
        {'video_views': 600776069, 'country_name': 'Canada', 'industry': None, 'hashtag': 'valentinesday', 'publish_count': 75979, 'trend_type': 'flat', 'is_new': None},
        {'video_views': 261310366, 'country_name': 'Canada', 'industry': None, 'hashtag': 'nativetiktok', 'publish_count': 83205, 'trend_type': 'flat', 'is_new': None},
        {'video_views': 428069314, 'country_name': 'Canada', 'industry': None, 'hashtag': 'repost', 'publish_count': 36489, 'trend_type': 'flat', 'is_new': None},
        {'video_views': 210873304, 'country_name': 'Canada', 'industry': None, 'hashtag': 'bsf', 'publish_count': 20090, 'trend_type': 'up', 'is_new': None},
        {'video_views': 340616661, 'country_name': 'Canada', 'industry': None, 'hashtag': 'r6', 'publish_count': 35419, 'trend_type': 'up', 'is_new': None},
        {'video_views': 355403472, 'country_name': 'Canada', 'industry': 'Apparel & Accessories', 'hashtag': 'outfit', 'publish_count': 32387, 'trend_type': 'up', 'is_new': None},
        {'video_views': 418673767, 'country_name': 'Canada', 'industry': None, 'hashtag': 'country', 'publish_count': 30624, 'trend_type': 'flat', 'is_new': True},
        {'video_views': 152020976, 'country_name': 'Canada', 'industry': 'Apparel & Accessories', 'hashtag': 'spring', 'publish_count': 45042, 'trend_type': 'up', 'is_new': None},
        {'video_views': 370026823, 'country_name': 'Canada', 'industry': 'Games', 'hashtag': 'rainbowsixsiege', 'publish_count': 28596, 'trend_type': 'up', 'is_new': None},
        {'video_views': 270628782, 'country_name': 'Canada', 'industry': 'Games', 'hashtag': 'warzone', 'publish_count': 32311, 'trend_type': 'up', 'is_new': None},
        {'video_views': 229623223, 'country_name': 'Canada', 'industry': None, 'hashtag': 'bestfriends', 'publish_count': 21519, 'trend_type': 'up', 'is_new': None},
        {'video_views': 202763032, 'country_name': 'Canada', 'industry': 'Pets', 'hashtag': 'doglover', 'publish_count': 34924, 'trend_type': 'up', 'is_new': None},
        {'video_views': 248690130, 'country_name': 'Canada', 'industry': None, 'hashtag': 'bestie', 'publish_count': 22239, 'trend_type': 'up', 'is_new': None},
        {'video_views': 256988387, 'country_name': 'Canada', 'industry': 'Games', 'hashtag': 'valorant', 'publish_count': 27847, 'trend_type': 'up', 'is_new': None},
        {'video_views': 295243227, 'country_name': 'Canada', 'industry': None, 'hashtag': 'her', 'publish_count': 15625, 'trend_type': 'up', 'is_new': None},
        {'video_views': 209109430, 'country_name': 'Canada', 'industry': 'Travel', 'hashtag': 'beach', 'publish_count': 25887, 'trend_type': 'up', 'is_new': None},
        {'video_views': 273823696, 'country_name': 'Canada', 'industry': None, 'hashtag': 'positivity', 'publish_count': 30189, 'trend_type': 'up', 'is_new': None},
    ]
    return data_df